title: Merilys Huhn
description: PhD Candidate<br>Stanford Sociology

markdown: kramdown
highlighter: rouge
paginate: 5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

sidebar_home_link:  true
